### ISSUE TITLE
Total cost is 0

### ISSUE THREAD

**Issue by justaboredkid** [justaboredkid/simple-railway-game#10]
Seattle - Tillamook
Government funding
All wages - $2
Per KM
Player C

`Total cost is $0. That is around $0.00 per KM. Are you sure? (Y/N)>^C`
`Traceback (most recent call last):`
`  File "main.py", line 543, in <module>`
`    build(key, 0)`
`  File "main.py", line 264, in build`
`    buildtrack(starting, build, player, 0)`
`  File "main.py", line 173, in buildtrack`
`    " per KM. Are you sure? (Y/N)>").lower()`
`KeyboardInterrupt`

**Comment by justaboredkid** [comment]
```
Player C:
Seattle
[['Moscow', 'Idaho', 694], ['Kamloops', 'British Columbia', 627], ['Calgary', 'Alberta', 979], ['Tillamook', 'Oregon', 515]]

Where to go? >calgary
Someone already got that station
Where to go? >tillamook
How many workers do you want to hire? (Type any letters to cancel)> 3000
ratio of workers (white) %>25
ratio of workers (immigrant/aboriginal) %>50
ratio of workers (black) %>25

```

**Comment by justaboredkid** [comment]
Wages from report could be incorrect. Further testing suggests $0 wages causes this.
